name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on EC2
        run: |
          # Setup SSH
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          
          # Connect to server and deploy
          ssh -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            # Remove previous project clone and clone the repository using credentials
            rm -rf factoria-f5 && \
            git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com/Diiego1500/factoria-f5.git && \
            cd factoria-f5

            # Clean previous container and image
            docker stop web >/dev/null 2>&1 || true
            docker rm web >/dev/null 2>&1 || true
            docker rmi web_image:latest >/dev/null 2>&1 || true

            # Build new Docker image
            docker build -t web_image:latest .

            # Run new container
            docker run -d --name web --network monolito_network -p 80:80 web_image:latest
          '
