name: Deploy Docker Container to EC2

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image Tag'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${{ inputs.image_tag }}" >> $GITHUB_ENV

      - name: SSH into EC2 and Deploy
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Pulling new Docker image..."
            docker pull dbastidas/imgmonolito:$IMAGE_TAG

            echo "Stopping old container..."
            docker stop myapp || true
            docker rm myapp || true

            echo "Starting new container..."
            docker run -d --name myapp -p 80:80 dbastidas/imgmonolito:$IMAGE_TAG

            echo "Connecting container to network..."
            docker network connect monolito_network myapp

            echo "Setting permissions on 'var' folder inside the container..."
            docker exec -it myapp bash -c 'chmod 777 -R var/'

            echo "Deployment complete!"
          EOF
