name: Deploy Docker Container to EC2

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image Tag'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        run: |
          # Configuración SSH
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

          # Comandos en el servidor
          ssh -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            # Actualizar versión de assets
            TIMESTAMP=$(date +%s)
            docker exec web sed -i "s/version: '\''v.*'\''/version: '\''v$TIMESTAMP'\''/g" /var/www/html/image_management/config/packages/framework.yaml

            # Despliegue sin reiniciar Apache
            docker pull dbastidas/imgmonolito:${{ inputs.image_tag }}
            docker stop web >/dev/null 2>&1 || true
            docker rm web >/dev/null 2>&1 || true
            docker run -d \
              --name web \
              --network monolito_network \
              -p 80:80 \
              dbastidas/imgmonolito:${{ inputs.image_tag }}
            docker exec web chmod -R 777 var
            docker exec web php ./vendor/bin/phpunit --testdox-html public/assets/unit-testing/results.html
          '
